services:
  rabbitmq:
    image: rabbitmq:latest
    ports:
      - "5672:5672" # rabbit amqp port
      - "15672:15672" # manage port
      - "61613:61613" # STOMP Port
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}  # 기본사용자 이름
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}  # 기본사용자 비밀번호
    command: >
      sh -c "rabbitmq-plugins enable rabbitmq_stomp &&
             rabbitmq-plugins enable rabbitmq_management &&
             rabbitmq-server"